INSERT INTO CATEGORY (ID, NAME) VALUES (1, 'VIDA');
INSERT INTO CATEGORY (ID, NAME) VALUES (2, 'AUTO');
INSERT INTO CATEGORY (ID, NAME) VALUES (3, 'VIAGEM');
INSERT INTO CATEGORY (ID, NAME) VALUES (4, 'RESIDENCIAL');
INSERT INTO CATEGORY (ID, NAME) VALUES (5, 'PATRIMONIAL');
